// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVg-bklu0UDJ2g6HHcPG6yD_K0FWcAWJc',
    appId: '1:296257558958:android:95862126e7f452353d103f',
    messagingSenderId: '296257558958',
    projectId: 'build-your-focus',
    storageBucket: 'build-your-focus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-2XfltI6cHm5KCKt8tx5dXGN8x4ZTXKc',
    appId: '1:296257558958:ios:4d6cd844a82a52f13d103f',
    messagingSenderId: '296257558958',
    projectId: 'build-your-focus',
    storageBucket: 'build-your-focus.firebasestorage.app',
    androidClientId: '296257558958-ohpgj8hrgnfopr0jgkv9ngl1tqdfbeh1.apps.googleusercontent.com',
    iosClientId: '296257558958-s0kf5fpm934iiuobcf8q2av03l40o4je.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildYourFocus',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7g08FMNtEOJ0Fmipzrkbwn3st1NnpcoM',
    appId: '1:296257558958:web:d528b98351527fae3d103f',
    messagingSenderId: '296257558958',
    projectId: 'build-your-focus',
    authDomain: 'build-your-focus.firebaseapp.com',
    storageBucket: 'build-your-focus.firebasestorage.app',
    measurementId: 'G-8QFRPZS7LX',
  );

}